### ISSUE TITLE
ODT support

### ISSUE THREAD

**Issue by Klap-in** [micgro42/dokuwiki-plugin-pagebreak#1]
The ODT plugin has an pagebreak function [1].
Can you implement that the render() calls this function for a odt?

The ODT renderer is associated with the mode `$mode == 'odt'`

[1] https://github.com/LarsGit223/dokuwiki-plugin-odt/blob/master/renderer.php#L862

**Comment by Klap-in** [comment]
@LarsGit223 Github has some nice trics:

For closing issues by committing, you could use:
Fixes #1
Close #1
See also https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by lpaulsen93** [comment]
Thanks for the tip.

**Comment by micgro42** [comment]
That is interesting to know, thank you @Klap-in .
