### ISSUE TITLE
Use of <pagebreak> creates invalid ODT document even though, not supported

### ISSUE THREAD

**Issue by lpaulsen93** [micgro42/dokuwiki-plugin-pagebreak#3]
If a <pagebreak> tag is inserted in a page and the page is exported to ODT then the created ODT document is invalid. This is strange because the plugin does not support ODT yet.

**Comment by micgro42** [comment]
Should be fixed by merging Pull Request #4

**Comment by lpaulsen93** [comment]
Thanks.
